AllCops:
  NewCops: enable
Style/StringLiterals:
  Exclude:
    - 'test/proto/addressbook_pb.rb'
Style/HashSyntax:
  Exclude:
    - 'test/proto/addressbook_pb.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/proto/addressbook_pb.rb'
Metrics/MethodLength:
  Max: 100