inherit_from: .rubocop_todo.yml

require: rubocop-rake
AllCops:
  NewCops: enable
  Exclude:
    - '**/*_pb.rb'
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 140
Layout/LineLength:
  Max: 150
