require: rubocop-rake
AllCops:
  NewCops: enable
Style/StringLiterals:
  Exclude:
    - '**/*_pb.rb'
Style/HashSyntax:
  Exclude:
    - '**/*_pb.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*_pb.rb'
Metrics/MethodLength:
  Max: 100
  Exclude:
    - '**/*_pb.rb'