inherit_from: .rubocop_todo.yml

# Preserve default Excludes (e.g., vendor/) to prevent linting cached gems.
inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - '**/*_pb.rb'
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 140
Layout/LineLength:
  Max: 150
