# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("log.proto", :syntax => :proto3) do
    add_message "Log" do
      optional :timestamp, :int64, 1
      optional :message, :string, 2
    end
  end
end

Log = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Log").msgclass
