name: Build and test

on:
  push:


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: 2.7
      - name: Install gems
        run: |
          bundle install
      - name: "Linting"
        run: "bundle exec rake lint:check"

  test:
    name: Unit testing with Ruby version ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.0'
          - '2.7'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Unit test"
        run: "bundle exec rake test:unit"

  build:
    name: Building gem with Ruby version ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.0'
          - '2.7'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: "Building gem"
        run: "bundle exec rake build"
